# This is the code for generating the Hubbard model Hamiltonian

In [1]:
import numpy as np
import pickle
from H_data_storage.data_interface import TensorData

## Here are the codes to preapre each term in the Hubbard Hamilotonian

In [4]:
def get_t_term(t, spatial_orb):
    """
    Prepares the t term of the Hubbard Hamiltonian.
    :param t: The strength of the t term
    :param spatial_orb: The number of spatial orbitals
    :return: the t term tensor of the Hamilotnian and the 1d version of it.
    """
    n = spatial_orb
    tensor = np.zeros((2 * n, 2 * n))

    one_body_1d = []
    for i in range(n-1):
        tensor[2 * i + 2, 2 * i] = 1
        tensor[2 * i + 3, 2 * i + 1] = 1
        tensor[2 * i, 2 * i + 2] = 1
        tensor[2 * i + 1, 2 * i + 3] = 1
        one_body_1d.append((2 * i + 2, 2 * i, t))
        one_body_1d.append((2 * i + 3, 2 * i + 1, t))
        one_body_1d.append((2 * i, 2 * i + 2, t))
        one_body_1d.append((2 * i + 1, 2 * i + 3, t))
    
    one_body_1d_data = TensorData(spatial_orb, one_body_1d)
    return tensor * t, one_body_1d_data


def get_u_term(u, spatial_orb):
    """
    Prepares the U term of the Hubbard Hamiltonian.
    :param u: The strength of the u term
    :param spatial_orb: The number of spatial orbitals
    :return: The u term tensor of the Hubbard Hamilotnian and the 1D array version of the tensor.
    """
    n = spatial_orb
    tensor = np.zeros((2 * n, 2 * n, 2 * n, 2 * n))
    
    two_body_1d = []
    for p in range(n):
        tensor[2 * p, 2 * p, 2 * p + 1, 2 * p + 1] = 1
        two_body_1d.append((2 * p, 2 * p, 2 * p + 1, 2 * p + 1, u))
    
    two_body_1d_data = TensorData(spatial_orb, two_body_1d)
    return tensor * u, two_body_1d_data

In [5]:
def test_hermitian(tensor):
    """
    Given a tensor, tests whether it is Hermitian
    :param tensor: The tensor to be tested
    :return: 
    """
    n = tensor.shape[0]
    if tensor.shape == (n, n):
        for p in range(n):
            for q in range(n):
                assert tensor[p, q] == tensor[q, p], "Hermitian test failed"
    elif tensor.shape == (n, n, n, n):
        for p in range(n):
            for q in range(n):
                for r in range(n):
                    for s in range(n):
                        assert tensor[p, q, r, s] == tensor[q, p, r, s], "Hermitian test failed"
                        assert tensor[p, q, r, s] == tensor[p, q, s, r], "Hermitian test failed"
    else:
        print("Tensor shape wrong")
    
def test_t_term_symmetry(tensor):
    """
    The t term should be symmetric. 
    :param tensor: The t-term tensor
    :return: 
    """
    # TODO
    
def test_u_term():
    """
    The u term should be
    :return: 
    """
    # TODO

## Set parameters

In [6]:
t_strength = 1
U_strength = 1
spatial_orb = 2

In [7]:
directory_path = "../H_data_storage/Hubbard_models/"
file_name = "Hubbard_t1_u1"

## Construct Hubbard Hamiltonians

In [8]:
t_term, t_term_1d_data = get_t_term(t_strength, spatial_orb)
u_term, u_term_1d_data = get_u_term(U_strength, spatial_orb)

In [9]:
test_hermitian(t_term)
test_hermitian(u_term)

In [49]:
print(t_term)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [50]:
data = dict()
data["obt_data"] = t_term_1d_data
data["tbt_data"] = u_term_1d_data

with open(directory_path + file_name + ".pkl", 'wb') as f:
  pickle.dump(data, f)
  
print("Data saved")

Data saved
