# This code compiles tensors to unitary gates

In [1]:
import numpy as np
from qiskit.circuit.library import UnitaryGate
from qiskit.quantum_info.operators import Operator, SparsePauliOp
import scipy
from scripts.database import Hubbard, DataManager, Tensor

In [2]:
def unitary_to_unitary_gate(unitary: np.ndarray):
    """
    Converts a tensor to unitary gates
    :param tensor: 
    :return: 
    """
    unitary_gate = UnitaryGate(unitary)
    print(unitary_gate)
    return unitary_gate

def unitary_to_sparse_pauli(unitary: np.ndarray):
    """
    Converts a tensor to sparse pauli operator
    :param tensor: 
    :return: 
    """
    operator = Operator(unitary)
    return SparsePauliOp.from_operator(operator)


In [3]:
def matrix_to_sparse_pauli(tensor: np.ndarray):
    """
    Converts a matrix to sparse pauli operator
    :param tensor: 
    :return: 
    """
    unitary = scipy.linalg.expm(tensor)
    return unitary_to_sparse_pauli(unitary)

In [4]:
h = Hubbard(2)  # create a Hubbard model of two spatial orbitals
h.decompose(1, 3)  # decompose into one- and two-body terms with coefficients of 1s
hd = h.get_decomp()  # get decomposition info
obt = hd.get_term('obt')  # get the one-body term
print(obt.matrix_1d)

[(2, 0, 1), (3, 1, 1), (0, 2, 1), (1, 3, 1)]


In [5]:
unitary = [[0, 0, 0, 1],
          [0, 0, 1, 0],
          [1, 0, 0, 0],
          [0, 1, 0, 0]]

gate = unitary_to_sparse_pauli(unitary)
print(gate)

SparsePauliOp(['XI', 'XX', 'YI', 'YX'],
              coeffs=[ 0.5+0.j ,  0.5+0.j , -0. -0.5j,  0. +0.5j])


In [6]:
tbt = hd.get_term('tbt')
print(tbt.matrix)

[[[[0. 0. 0. 0.]
   [0. 1. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 1.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0

In [8]:
unitary2 = scipy.linalg.expm(tbt.matrix)

In [10]:
unitary_to_sparse_pauli(unitary2)

QiskitError: 'Input shape is not 1 or 2-dimensional (shape = (4, 4, 4, 4))'